baseurl = "https://planette.vercel.app/"
languageCode = "en-us"
title = "Planette - Tutorials, examples, snippets and other dev tools"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[params]
    github = "https://github.com/contributte/planette-site/"
    github_content = "https://github.com/contributte/planette-site/blob/master/content/"
